### ISSUE TITLE
Copy the snippets to Javascript

### ISSUE THREAD

**Issue by olivierperez** [olivierperez/kata-shame-on-it#3]
Create a new folder `/snippets/javascript`.
I'll move the kotlin snippets myself, I'm currently working on one.

**Comment by bilalbutt044** [comment]
can i work on it ?

**Comment by olivierperez** [comment]
Sure, can you create a new folder "/snippets/javascript"?
I'll move the kotlin snippets myself, I'm currently working on one.
*And I'll edit the text of this issue*

**Comment by bilalbutt044** [comment]
do you mean I have to just creat a folder named javascript?

**Comment by olivierperez** [comment]
Hmmm, currently there is `kotlin/snippets`, but I'll move it to `snippets/kotlin`.
Can you create the folder `snippets/java`?

**Comment by bilalbutt044** [comment]
i created a folder `javascript` inside `snippets`.
I want to ask do i have to just create folder and submit pull request? or i have to convert in JS too ?

**Comment by olivierperez** [comment]
Convert it plz

**Comment by bilalbutt044** [comment]
well this code in Kotlin which strongly types language whereas JavaScript is not typed language.
for example we cannot difine parameter type by class name like we can do in Kotlin or Java. 
So how i convert this in JS?

**Comment by olivierperez** [comment]
You are right, it could be difficult to convert from Kotlin to JavaScript because of this. I didn't think about it before.
I propose you something, if you think one of this snippets is still convertable: do it. I've split this issue into 6 to decrease the amount of work required for a PR :wink: => #7 #8 #9 #10 #11 #12 

By the way, thanks for this analysis :+1: 

_I'll close this one_
